### ISSUE TITLE
fabfile - not rebuilding messages.mo ?

### ISSUE THREAD

**Issue by balmas** [perseids-project/perseids-client-apps#12]
@PonteIneptique am I missing a step in the fabfile to regenerate the messages.mo binary files?  I added a new string to the treebank form, and updated the en and fr messages files, but the deployment isn't picking up the new string, just the default from the template, and I'm guessing it's because messages.mo isn't regenerated?

We really need to document the deployment steps for this...

**Comment by PonteIneptique** [comment]
If I remember well, .mo files have nothing to do with fab... The i18n section on the README.md does not work ?

**Comment by balmas** [comment]
Well, I followed the readme, but maybe the problem was that I didn't use Poedit to edit the file?

I did the following:

1) Updated the template to include a new message string
2) Ran `pybabel - extract -F babel.cfg -k lazy_gettext -o messages.pot app` to re-extract the messages
3) Ran `pybabel update -i messages.pot -d app/translations -l $LANGUAGE` to update the existing language files
4) manually edited the messages.po files to edit the automatically generated strings.
5) Committed the updated files (messages.pot, messages.po (x 2) and the new template html) 
6) ran the fab deploy
