### ISSUE TITLE
move the mongo_db_ops and save data functionality to the digital_milliet app

### ISSUE THREAD

**Issue by balmas** [perseids-project/perseids-client-apps#21]
not sure how this is working live, but when I run the app locally, it can't find this file.

per @PonteIneptique the solution is to change the following in the importing code (views.py):

`from mongo_db_ops import add_to_db`
to
`from app.mongo_db_ops import add_to_db`

**Comment by balmas** [comment]
we want to move all the mongodb code out of here anyway .. see https://github.com/PerseusDL/digital_milliet/issues/18

**Comment by annakrohn** [comment]
Completed in viewsclean branch.  https://github.com/perseids-project/perseids-client-apps/tree/viewsclean
